### ISSUE TITLE
Good link for semver

### ISSUE THREAD

**Issue by ThorodanBrom** [iudx/software-engineering#1]
In Best Practices, a link to a good description of semver can be added. For example,
* https://www.jvandemo.com/a-simple-guide-to-semantic-versioning/

**Comment by pct960** [comment]
Thanks, I'll add the link.

**Comment by pct960** [comment]
Added in https://github.com/iudx/software-engineering/commit/3035f3dfe75327bc5c4864b7847a66f08e1649af
